name: Deploy to Google Cloud Run on push to main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # env:
    #   NIXPKGS_ALLOW_UNFREE: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Cache install Nix packages
        uses: DeterminateSystems/nix-installer-action@main
      - name: Cache rust dependencies and build output
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/x86_64-unknown-linux-musl/release/
          key: rust-${{ hashFiles('**/Cargo.lock') }}
      - name: Run database migrations
        run: nix-shell --run 'sqlx migrate run'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Build Rust project to `musl` output
        run: nix-shell --run 'cargo build --release --target x86_64-unknown-linux-musl'
        # env:
        #   DATABASE_URL: ${{ secrets.DATABASE_URL }}
