name: Deploy to Google Cloud Run on push to main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Cache install Nix packages
        uses: rikhuijzer/cache-install@v1.0.9
        with:
          key: nix-${{ hashFiles('default.nix') }}
