name: Deploy to Google Cloud Run on push to main
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: hot-or-not-monitoring
  DEPLOY_REGION: us-central1
  IMAGE_NAME: receive_canister_metrics_from_fleet_and_push_to_timeseries_database
  SERVICE_NAME: receive-canister-metrics-and-push-to-timeseries-database

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Nix packages
        uses: DeterminateSystems/nix-installer-action@main
      - name: Cache Nix packages
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Cache rust dependencies and build output
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            target/
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run database migrations
        run: nix-shell --run 'sqlx migrate run'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Build Rust project to `musl` output
        run: nix-shell --run 'cargo build --release --target x86_64-unknown-linux-musl'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
      - name: Docker auth
        run: |-
          gcloud auth configure-docker ${{ env.DEPLOY_REGION }}-docker.pkg.dev
      - name: "Build and push container"
        run: |-
          docker build . --tag ${{ env.DEPLOY_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.DEPLOY_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
      - name: Deploy to cloud run
        id: deploy
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: ${{ env.SERVICE_NAME }}
          image: ${{ env.DEPLOY_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          region: ${{ env.DEPLOY_REGION }}
          project_id: ${{ env.PROJECT_ID }}
          flags: "--allow-unauthenticated --max-instances=1 --cpu=2 --memory=2Gi --concurrency=1000"
          env_vars: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
