name: Deploy to Google Cloud Run on push to main
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Nix packages
        uses: DeterminateSystems/nix-installer-action@main
      - name: Cache Nix packages
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Cache rust dependencies and build output
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            target/
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run database migrations
        run: nix-shell --run 'sqlx migrate run'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Build Rust project to `musl` output
        run: nix-shell --run 'cargo build --release --target x86_64-unknown-linux-musl'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/431003668404/locations/global/workloadIdentityPools/receive-canister-metrics/providers/github-action"
          service_account: "github-action@hot-or-not-monitoring.iam.gserviceaccount.com"
      - name: Deploy to cloud run
        id: deploy
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: "receive-canister-metrics-and-push-to-timeseries-database"
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          secrets: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
